Repository KenyaSugimoto/RitsChiebukuro, pull requests merged in 2020-08, with the labels that each got.

#10 #4ルーティングのガードを関数化する
  src/main.js
  src/router.js
Labels: omachi

#19 #18/HTML構成調整
  src/App.vue
  src/components/global/Header.vue
Labels: kenya

#21 #3ユーザーのuidをvuexで管理する
  src/store/index.js
  src/store/modules/auth.js
  src/store/modules/login.js
  src/store/modules/logout.js
  src/store/modules/register.js
Labels: omachi

#25 Headerに関するルーティングの修正
  src/router.js
Labels: omachi

#30 #22ユーザ登録時にユーザの情報をユーザテーブルに登録する
  src/App.vue
  src/components/pages/SignUp.vue
  src/main.js
  src/router.js
  src/store/index.js
  src/store/modules/register.js
  src/store/modules/signUp.js
Labels: omachi

#37 login.jsのインデント修正
  src/store/modules/login.js
Labels: omachi

#44 #33「回答」ページ削除
  src/components/global/Header.vue
  src/router.js
Labels: kenya

#43 #38 axios-post.js → axios-db.jsに変更
  src/axios/axios-db.js
  src/store/modules/contents.js
  src/store/modules/signUp.js
Labels: kenya

#47 登録済みのメアドで登録しようとしたときのエラー文の表示
  src/store/modules/signUp.js
Labels: omachi

#55 #41vuex persistedstateの導入
  package-lock.json
  package.json
  src/App.vue
  src/store/index.js
  src/store/modules/auth.js
  src/store/modules/login.js
Labels: omachi

#59 #29重複するユーザidは登録できないようにする
  src/axios/axios-auth.js
  src/axios/axios-db.js
  src/axios/axios-query.js
  src/axios/axios-refresh.js
  src/components/pages/SignUp.vue
  src/store/modules/logout.js
  src/store/modules/signUp.js
Labels: omachi

#61 ログアウト時にstateの内容を初期化する
  src/store/index.js
  src/store/modules/logout.js
Labels: omachi

#72 メール認証
  src/components/pages/ActivateAccount.vue
  src/components/pages/Login.vue
  src/main.js
  src/router.js
  src/store/index.js
  src/store/modules/auth.js
  src/store/modules/getUserInfo.js
  src/store/modules/login.js
  src/store/modules/logout.js
  src/store/modules/signUp.js
Labels: omachi

#74 #62新着一覧ページネーション
  package.json
  public/index.html
  src/App.vue
  src/components/global/Header.vue
  src/components/pages/Category.vue
  src/components/pages/TopPage.vue
  src/components/parts/Search.vue
  src/main.js
  src/plugins/vuetify.js
  src/router.js
  vue.config.js
Labels: akiyama

#80 #45 ログインユーザの新着投稿をマイページで表示
  src/components/pages/MyPage.vue
  src/store/index.js
  src/store/modules/contents.js
Labels: kenya

#81 #56gettersとmutationsもindex.jsの中で分割する
  src/store/index.js
Labels: omachi

#83 投稿時間が見にくいので修正
  src/components/pages/MyPage.vue
  src/components/pages/TopPage.vue
  src/main.js
Labels: omachi

#86 #65パスワード確認フォームの作成
  src/components/pages/Login.vue
  src/components/pages/SignUp.vue
Labels: omachi

#90 #88ユーザ名の登録時大文字が入ってたら登録できないのを直す
  src/components/pages/SignUp.vue
Labels: omachi

#91 #77 質問投稿時にカテゴリを選択できるようにした
  src/components/pages/MyPage.vue
  src/components/pages/TopPage.vue
  src/store/modules/contents.js
  src/store/modules/getUserInfo.js
  src/store/modules/signUp.js
Labels: kenya

#93 #85/未投稿のユーザがマイページに入っても大丈夫なようにする
  src/store/modules/contents.js
  src/store/modules/getUserInfo.js
  src/store/modules/signUp.js
Labels: kenya

#92 #87 カテゴリ別に表示
  src/components/pages/Category.vue
  src/store/index.js
  src/store/modules/contents.js
Labels: kenya

#97 #89パスワードの再設定機能
  src/App.vue
  src/components/pages/ActivateAccount.vue
  src/components/pages/Category.vue
  src/components/pages/Login.vue
  src/components/pages/ResetPassword.vue
  src/components/pages/SignUp.vue
  src/components/pages/TopPage.vue
  src/main.js
  src/router.js
  src/store/index.js
  src/store/modules/login.js
  src/store/modules/reset.js
Labels: omachi

#98 #95ログイン失敗時にユーザに知らせる
  src/store/modules/login.js
Labels: omachi

#99 #96クエリの共通部分の定数化
  src/store/modules/contents.js
Labels: omachi

#101 #100質問一覧をカスタムタグで部品化する
  src/components/pages/Category.vue
  src/components/pages/MyPage.vue
  src/components/pages/Posts.vue
  src/components/pages/TopPage.vue
Labels: omachi

#104 #103Posts.vueの修正
  src/components/pages/Posts.vue
Labels: omachi

#105 #78質問の個別ページ
  src/components/pages/Post.vue
  src/components/pages/Posts.vue
  src/router.js
Labels: omachi

#108 #107質問の個別ページを作り込む
  src/components/pages/Post.vue
  src/components/pages/Posts.vue
  src/components/pages/SignUp.vue
  src/store/index.js
Labels: omachi

#116 #79質問削除ボタン
  src/components/pages/Post.vue
  src/components/pages/Posts.vue
  src/store/modules/contents.js
Labels: omachi

#119 #115投稿を押した後に質問カテゴリの値をリセット
  src/components/pages/TopPage.vue
Labels: omachi

#122 #121Postsタグに引数を追加
  src/components/pages/Category.vue
  src/components/pages/Login.vue
  src/components/pages/MyPage.vue
  src/components/pages/Post.vue
  src/components/pages/Posts.vue
  src/components/pages/ResetPassword.vue
  src/components/pages/SignUp.vue
  src/components/pages/TopPage.vue
  src/store/modules/login.js
Labels: omachi

#139 #131回答、コメント機能の実装
  src/components/pages/Post.vue
  src/store/index.js
  src/store/modules/thread.js
Labels: omachi

#148 #140回答、コメントに削除ボタンをつける
  src/components/pages/Post.vue
  src/store/modules/post.js
  src/store/modules/thread.js
Labels: omachi

#150 #142質問のドキュメントIDを指定する
  src/store/modules/post.js
Labels: omachi

#162 #151キーワード検索機能
  package-lock.json
  package.json
  src/components/global/Header.vue
  src/components/pages/PostCompleted.vue
  src/components/pages/SearchResult.vue
  src/components/pages/TopPage.vue
  src/components/parts/Search.vue
  src/function/segmentText.js
  src/router.js
  src/store/index.js
  src/store/modules/post.js
  src/store/modules/search.js
Labels: omachi

#166 #163回答ボタンを押した時にisAnswered更新
  src/components/pages/Post.vue
  src/store/modules/post.js
Labels: omachi

#169 #167ベストアンサー機能
  src/components/pages/Post.vue
  src/store/modules/post.js
  src/store/modules/thread.js
Labels: omachi

#172 今あるアラートをトーストに変えました
  package-lock.json
  package.json
  src/components/pages/Post.vue
  src/components/pages/ResetPassword.vue
  src/components/pages/SignUp.vue
  src/components/pages/TopPage.vue
  src/function/toastr.js
  src/main.js
  src/store/index.js
  src/store/modules/login.js
  src/store/modules/post.js
  src/store/modules/reset.js
  src/store/modules/signUp.js
  src/store/modules/thread.js
Labels: akiyama

#178 #168トップページに新着質問と回答受付中の質問を表示
  src/components/pages/Category.vue
  src/components/pages/MyPage.vue
  src/components/pages/Posts.vue
  src/components/pages/TopPage.vue
  src/main.js
  src/store/modules/thread.js
Labels: omachi

#180 toastに表示する文字を修正
  src/store/modules/thread.js
Labels: omachi

#177 #165/通知の消し方について
  src/components/pages/Post.vue
  src/components/parts/Notification.vue
  src/store/index.js
  src/store/modules/notification.js
  src/store/modules/signUp.js
Labels: kenya

#181 #173閲覧数カウント機能
  src/components/pages/Post.vue
  src/store/index.js
  src/store/modules/logout.js
  src/store/modules/post.js
Labels: omachi

#182 #174confirmもいい感じに
  package-lock.json
  package.json
  src/components/pages/Post.vue
  src/components/pages/SignUp.vue
  src/components/pages/TopPage.vue
  src/main.js
Labels: omachi

#186 #184よく見られている質問の作成
  src/components/pages/Category.vue
  src/components/pages/MyPage.vue
  src/components/pages/Post.vue
  src/components/pages/TopPage.vue
  src/main.js
  src/store/index.js
  src/store/modules/getUserInfo.js
  src/store/modules/login.js
  src/store/modules/post.js
  src/store/modules/signUp.js
  src/store/modules/user.js
Labels: omachi

#191 Confirmの修正
  src/components/pages/Post.vue
  src/components/pages/SignUp.vue
  src/components/pages/TopPage.vue
  src/function/dialog.js
Labels: omachi

#193 #192ベストアンサーが削除されたときに回答欄が表示されないバグ修正
  src/components/pages/Post.vue
  src/store/index.js
  src/store/modules/thread.js
Labels: omachi

#196 #194Post.vueのリファクタリング
  src/components/pages/Post.vue
  src/store/modules/post.js
  src/store/modules/thread.js
  src/store/modules/user.js
Labels: omachi

#198 #195お気に入りの投稿を表示
  src/components/pages/Favorite.vue
  src/components/pages/MyPage.vue
  src/components/pages/MyPosts.vue
  src/main.js
  src/router.js
  src/store/modules/post.js
Labels: omachi

#201 #199パスワード変更ページの作成
  package-lock.json
  package.json
  src/components/global/Header.vue
  src/components/pages/MyPage.vue
  src/main.js
  src/router.js
  src/store/index.js
  src/store/modules/logout.js
Labels: omachi

#203 #202ログインページの整理
  src/App.vue
  src/components/global/Header.vue
  src/components/pages/ActivateAccount.vue
  src/components/pages/Login.vue
  src/components/pages/ResetPassword.vue
  src/components/pages/SearchResult.vue
  src/components/pages/SignUp.vue
  src/store/index.js
Labels: omachi

#206 #171ログインページのバリデーション
  src/components/pages/Login.vue
Labels: akiyama

#208 #190/回答者への通知機能
  src/components/pages/MyPage.vue
  src/components/pages/NotificationConfig.vue
  src/components/pages/Post.vue
  src/components/parts/Notification.vue
  src/router.js
  src/store/index.js
  src/store/modules/notification.js
  src/store/modules/post.js
  src/store/modules/thread.js
Labels: kenya

#214 #210 通知表示バグの修正
  src/components/pages/NotFoundPost.vue
  src/components/parts/Notification.vue
  src/router.js
  src/store/modules/post.js
Labels: kenya

#212 #221dialogの修正
  src/components/pages/Post.vue
  src/components/pages/SignUp.vue
  src/components/pages/TopPage.vue
  src/function/dialog.js
Labels: omachi

#215 #213ユーザ設定変更ページの作成
  src/components/pages/MyPage.vue
  src/components/pages/SignUp.vue
Labels: omachi

#217 #216Postに飛ぶ前にPostの存在を確認
  src/components/pages/Posts.vue
Labels: omachi

#221 #220Vuetify導入
  babel.config.js
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/main.js
  src/plugins/vuetify.js
Labels: omachi

#223 ボタン変更
  src/components/pages/Login.vue
  src/components/pages/Post.vue
  src/components/pages/SignUp.vue
  src/components/pages/TopPage.vue
Labels: omachi
